from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, Sequence

from document_mgmt_service.domain.models import (
    DocumentIngestionResult,
    DocumentPrivacyClassification,
    DocumentProcessingStatus,
    DocumentSummaryRecord,
    DocumentStatusResponse,
    DocumentVersionRecord,
)


class PostgreSQLDocumentRepository(Protocol):
    def ping(self) -> None: ...

    def ensure_schema(self) -> None: ...

    def next_version(self, document_id: str) -> int: ...

    def upsert_version(self, record: DocumentVersionRecord) -> None: ...

    def get_version(self, document_id: str, version: int) -> DocumentVersionRecord | None: ...

    def list_versions(self, document_id: str) -> list[DocumentVersionRecord]: ...

    def list_documents(self) -> list[DocumentSummaryRecord]: ...

    def delete_document(
        self, document_id: str, version: int | None = None, user_id: str | None = None
    ) -> list[str]: ...

    def close(self) -> None: ...


class QdrantVectorStore(Protocol):
    def ping(self) -> None: ...

    def upsert(self, document_id: str, vector: Sequence[float], payload: dict[str, object]) -> None: ...

    def search(self, vector: Sequence[float], limit: int = 10) -> list[dict[str, Any]]: ...

    def delete(self, document_id: str) -> None: ...

    def close(self) -> None: ...


class OCRService(Protocol):
    def ping(self) -> None: ...

    def extract_text(self, file_path: Path) -> str: ...

    def close(self) -> None: ...


class FileStorage(Protocol):
    def ping(self) -> None: ...

    def put(self, source: Path, destination_key: str) -> str: ...

    def get(self, storage_key: str) -> Path: ...

    def delete(self, storage_key: str) -> None: ...

    def exists(self, storage_key: str) -> bool: ...

    def close(self) -> None: ...


class UUIDFactory(Protocol):
    def __call__(self) -> str: ...


class Clock(Protocol):
    def __call__(self) -> Any: ...
