"""Port interfaces for the Web Search Service."""
from __future__ import annotations
from typing import Protocol
from web_search_service.domain.models import (
    CrawlRequest, CrawlResult, DownloadRequest, DownloadResult,
    FetchRequest, FetchResult,
    ScrapeRequest, ScrapeResult, SearchQuery, SearchResponse,
)


class WebSearchProvider(Protocol):
    def search(self, query: SearchQuery) -> SearchResponse: ...
    def ping(self) -> None: ...
    def close(self) -> None: ...


class WebScraperProvider(Protocol):
    def scrape(self, request: ScrapeRequest) -> ScrapeResult: ...
    def crawl(self, request: CrawlRequest) -> CrawlResult: ...
    def ping(self) -> None: ...
    def close(self) -> None: ...


class UrlFetcher(Protocol):
    def fetch(self, request: FetchRequest) -> FetchResult: ...
    def ping(self) -> None: ...
    def close(self) -> None: ...


class FileDownloader(Protocol):
    def download(self, request: DownloadRequest) -> DownloadResult: ...
    def ping(self) -> None: ...
    def close(self) -> None: ...
